nickname: eric
age: 20

#user:
#  nickname: jack
#  age: 18

#user:
#  list: eric,jack,rose

#user:
#  list:
#  - eric
#  - jack
#  - rose

#user:
#  map: "{nickname: 'eric',age: 20}"

user:
  map2: {nickname: eric,age: 20}

spring:
 devtools:
   restart:
     enabled: true  #设置开启热部署
     additional-paths: src/main/java #重启目录
     exclude: WEB-INF/**
 freemarker:
   cache: false    #页面不加载缓存，修改即时生效