spring:
  datasource: #修改数据库连接配置
    url: jdbc:mysql://localhost:3306/mybatis?characterEncoding=UTF8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

# mybatis配置
mybatis:
  type-aliases-package: com.yiidian.domain # 别名目录